### ISSUE TITLE
An error ocurred. Try refreshing your browser

### ISSUE THREAD

**Issue by logistic-people-deutschland** [PawanOsman/chatgpt-io#14]
I get the following error with the example

node examples/index1.js 
[INFO] 2023-02-13 15:23:27 Connected to server
[WARN] 2023-02-13 15:23:28 Session token changed, re-authenticating the new session token...
[INFO] 2023-02-13 15:23:31 Ready!
[ERROR] 2023-02-13 15:23:32 An error ocurred. Try refreshing your browser.
file:///var/www/.../chatgpt-io-main/node_modules/chatgpt-io/dist/classes/chatgpt.js:251
            throw new Error(data.error);
                  ^

Error: An error ocurred. Try refreshing your browser.
    at ChatGPT.send (file:///var/www/.../chatgpt-io-main/node_modules/chatgpt-io/dist/classes/chatgpt.js:251:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPT.ask (file:///var/www/.../chatgpt-io-main/node_modules/chatgpt-io/dist/classes/chatgpt.js:260:20)
    at async file:///var/www/.../chatgpt-io-main/examples/index1.js:9:18

Node.js v18.13.0

**Comment by PawanOsman** [comment]
if your account is plus then you need to set account type to plus

**Comment by PawanOsman** [comment]
please update to latest version
