### ISSUE TITLE
The server seems to go down today, can you help to fix it?

### ISSUE THREAD

**Issue by Troylee-rpi** [PawanOsman/chatgpt-io#3]
Thanks for providing such a good API for us, and I am happy using it recently. Could you please check this server and restart it ? 
I really appreciate that !

**Comment by PawanOsman** [comment]
Hey, sorry for the recent downtime that was caused by a limitation or issue from OpenAI.
we already fixed it now all 13 bypass servers are working

**Comment by ajeecai** [comment]
Could I ask what the server API IP or domain is? Is it available for public access? Could not find this information in the README.

Thanks

**Comment by optionsx** [comment]
> 

if you look through the code you would see a socket subdomain endpoint
